config/routes.rb
Findr::Application.routes.draw do
  get "static_pages/home"
  root "static_pages#home"
  
  resources :search_items, :path => "search"
  
  resources :users
  resource :session

end

app/models/search_item.rb
require 'json'
require 'addressable/uri'
require 'rest-client'

class SearchItem < ActiveRecord::Base
  
  def self.full_address(address)
    #get full address and zip
    address_request = Addressable::URI.new(
      :scheme => "https",
      :host => "maps.googleapis.com",
      :path => "maps/api/geocode/json",
      :query_values => {
        address: address,
      }
    ).to_s
    
    address_results = JSON.parse(RestClient.get(address_request))
    
    return nil if address_results["status"] == "ZERO_RESULTS"
    
    {
      address: address_results["results"][0]["formatted_address"],
      zip: address_results["results"][0]["address_components"].select{|hash| hash["types"][0] == "postal_code"}[0]["long_name"]
    }
  end
  
  def self.wifi_locations(address, zip)
    #free wifi locations NYC:
    @url = "https://data.cityofnewyork.us/api/views/4u6b-frhh/rows.json"

    @address = address
    @zip = zip
    
    #parse the URL results with JSON
    results = JSON.parse(RestClient.get(@url))
  
    #get only the addresses where the data matches 
    #up with free wifi and our zip code
    results = results["data"]
      .map { |location| location[9..-1] }
      .select { |result| result[6] == @zip && result[-2].strip == "Free" }
  
    #turns the location information into an address
    #that is then pumped into the google distance
    #api. a distance is then added to each location
    
    destination_addresses = ""
    results.each do |location|
      destination_addresses += "#{location[1]}, #{location[2]}, NY #{location[6]} |"
    end
      
    request = Addressable::URI.new(
      :scheme => "https",
      :host => "maps.googleapis.com",
      :path => "maps/api/distancematrix/json",
      :query_values => {
        origins: @address,
        destinations: destination_addresses,
        mode: "walking"
      }
    ).to_s
  
    distances = JSON.parse(RestClient.get(request))
    
    results.each_with_index do |location, index|
      location << distances["rows"][0]["elements"][index]["distance"]["text"].to_f
    end
    
    #sort results by shortest distance and then display
    #only the top 10
    results.sort! {|a, b| a[-1] <=> b[-1]}
    results[0..9]
  end
  
  # turns out these aren't public!
  # def self.bathroom_locations(address)
  #   @url = "https://data.cityofnewyork.us/api/views/h87e-shkn/rows.json"
  #   address_results = self.full_address(address)
  #
  #   return nil unless address_results
  #
  #   @address = address_results[:address]
  #   @zip = address_results[:zip]
  #
  #   results = JSON.parse(RestClient.get(@url))
  # end

end

app/models/user.rb
require 'bcrypt'

class User < ActiveRecord::Base
  attr_reader :password
  
  validates :username, :password_digest, presence: true
  validates :password, length: { minimum: 6 }, presence: true, allow_nil: true
  
  def self.find_by_credentials(username, password)
    user = User.find_by_username(username)
    return nil if user.nil?
    return user if BCrypt::Password.new(user.password_digest).is_password?(password)
  end
  
  def password=(password)
    self.password_digest = BCrypt::Password.create(password)
    @password = password
  end
  
  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64(16)
    self.save!
    self.session_token
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  helper_method :signed_in?, :current_user
  
  def current_user
    return nil unless session[:token]
    @current_user ||= User.find_by_session_token(session[:token])
  end
  
  def sign_in(user)
    @current_user = user
    session[:token] = user.reset_session_token!
  end
  
  def sign_out
    @current_user = nil
    session[:token] = nil
  end
  
  def signed_in?
    current_user.present?
  end
end

app/controllers/search_items_controller.rb
class SearchItemsController < ApplicationController
  before_action :check_if_signed_in
  
  def index
  end
  
  def new
  end
  
  def create
    address_results = SearchItem.full_address(search_params[:address])
    
    if !address_results
      flash.now[:errors] = ["Hmm, invalid address. Try again!"]
      render :new
    else
      @address = address_results[:address]
      @zip = address_results[:zip]
      @searches = (SearchItem.where(origin: @address) || [])
    
      if @searches.length == 0
        searches = SearchItem.wifi_locations(@address, @zip)

        searches.each do |search|
          search_item = SearchItem.new()
          search_item.name = search.shift
          search_item.address = search.shift
          search_item.origin = @address
          search_item.distance = search.pop
          search_item.search_type = "wifi"
          search.each do |el|
            search_item.url = el if el.match(/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(([0-9]{1,5})?\/.*)?$/ix)
            search_item.phone_number = el if el.match(/^(?:(?:\+?1\s*(?:[.-]\s*)?)?(?:\(\s*([2-9]1[02-9]|[2-9][02-8]1|[2-9][02-8][02-9])\s*\)|([2-9]1[02-9]|[2-9][02-8]1|[2-9][02-8][02-9]))\s*(?:[.-]\s*)?)?([2-9]1[02-9]|[2-9][02-9]1|[2-9][02-9]{2})\s*(?:[.-]\s*)?([0-9]{4})(?:\s*(?:#|x\.?|ext\.?|extension)\s*(\d+))?$/)
          end
          search_item.user_id = current_user.id
          search_item.save!
          @searches.push(search_item)
        end
      end
    
      render :index, :locals => { :searches => @searches }
    end
  end
  
  private
  
  def search_params
    params.require(:search).permit(:address, :type)
  end
  
  def check_if_signed_in
    unless signed_in?
      flash[:errors] = ["You need to sign in!"]
      redirect_to new_session_url
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    @user = User.find_by_credentials(user_params[:username], user_params[:password])
    
    if @user
      sign_in @user
      redirect_to @user
    else
      flash.now[:error] = ["Invalid credentials"]
      render :new
    end
  end
  
  def destroy
    sign_out
    redirect_to new_session_url
  end
  
  private
  
  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :check_if_correct_user, :only => [:show]
  
  def new
  end
  
  def create
    @user = User.new(user_params)
    
    if @user.save
      sign_in @user
      redirect_to @user
    else
      flash.now[:error] = @user.errors.full_messages
      render :new
    end
  end
  
  def show
    @user = User.find(params[:id])
  end
  
  private
  
  def user_params
    params.require(:user).permit(:username, :password)
  end
  
  def check_if_correct_user
    @user = User.find(params[:id])
    unless signed_in? && current_user.id == @user.id
      flash[:errors] = ["You need to sign in!"]
      redirect_to new_session_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def auth_token
    <<-HTML.html_safe
    <input type="hidden" 
           name="authenticity_token"
           value="#{form_authenticity_token}">
    HTML
  end
  
  def hidden_method(method)
    <<-HTML.html_safe
    <input type="hidden" 
           name="_method"
           value="#{method}">
    HTML
  end
end

app/helpers/search_items_helper.rb
module SearchItemsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Findr</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<%= render partial: "shared/flash" %>
	<%= render partial: "shared/navbar" %>
	
    <div class="<%= "jumbotron" if current_page?(root_url) %>">
      <div class="container">
        <%= yield %>
      </div>
    </div>

</body>
</html>

app/views/search_items/index.html.erb
<% if searches.empty? %>
	<br>
    <div class="alert alert-warning">
      Nothing found for that address!
    </div>
<% else %>
	<% searches.each do |search| %>
		<br>
		<div class="panel panel-primary">
		    <div class="panel-heading">
		      <h3 class="panel-title"><span class="glyphicon glyphicon-pushpin"></span><%= " #{search.name}" %></h3>
		    </div>
		    <div class="panel-body">
			  <%= search.address if search.address %><br>
			  <%= search.phone_number if search.phone_number %><br>
			  <% if search.url %>
				  <a href="<%= search.url %>"><%= search.url %></a><br>
			  <% end %>
			  <%= "Distance: #{search.distance} miles" %>
		    </div>
		</div>
	<% end %>
<% end %>

app/views/search_items/new.html.erb
<script type="text/javascript">
	$(document).ready(function(){
		$('#submit').click(function() {
			$('#spinner').show();
		});
	});
		
</script>

<h1>Search</h1>
<form action="<%= search_items_url %>" method="post">
    <%= auth_token %>
	
	<label>Gimme your address!
		<div class="input-group">
			<input type="text" name="search[address]" class="form-control" placeholder="Address">
		</div>
	</label>

	<br><br>

	<label>What're you looking for?
		<div class="select-style">
		  <select>
		    <option name="search[type]" value="wifi">Wifi</option>
		    <!-- <option value="search[type]" value="bathroom">Public Bathrooms</option>
		    <option value="search[type]" value="water">Water Fountains</option> -->
		  </select>
		</div>
	</label>
	
	<br><br>

	<input id="submit" type="submit" value="Submit">
</form>

<br><br>

<div id="spinner" style="display:none;">
	<h3>Loading!</h3><h4>Give me a second here...</h4><br>
	<img src="/assets/spinner.gif" alt="Spinner" >
</div>

app/views/shared/_flash.html.erb
<% if !flash.empty? %>
<div class="container" id="alerts">
<% flash.each do |key, value| %>
	<% value.each do |message| %>
	<% next if message.include?("Password is too short") && value.include?("Password can't be blank") %>
	
    <div class="alert alert-danger">
      <%= message %>
    </div>
		
    <% end %>
<% end %>
</div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
	
  <div class="container">        
    <ul class="nav navbar-nav">
      <li <%= "class=active" if current_page?(root_url) %>>
        <a href="/">Home</a>
      </li>
	  <li <%= "class=active" if params["controller"] == "search_items" %>>
		<a href="/search/new">Search</a>
	  </li>
    </ul>
    
    <ul class="nav navbar-nav navbar-right">
		<% if signed_in? %>
			<div class="navbar-brand">
		   		<%= "logged in as #{current_user.username}" if signed_in? %>
	   		</div>
			<li>
			<form action="<%= session_url %>" class="navbar-form navbar-left" method="post">
				<%= auth_token %>
				<%= hidden_method("delete") %>
    			<button type="submit" class="btn btn-default">Sign Out</button>
			</form>
			</li>
		<% else %>
			<li>
			<div class="navbar-form navbar-left">
    			<a href="<%= new_session_url %>" class="btn btn-default">Sign In</a>
			</div>
			</li>
		<% end %>
    </ul>
  </div>
</div>

app/views/shared/_user.html.erb
<%= auth_token %>  

<label>
	Username<br>
	<div class="input-group"><input type="text" id="input-username" name="user[username]" class="form-control" placeholder="Username"></div>
</label>

<br>

<label visible=false>
	Password<br>
	<div class="input-group"><input type="password" id="input-password" name="user[password]" class="form-control" placeholder="Password"></div>
</label>

<br><br>

app/views/static_pages/home.html.erb
<span class="glyphicon glyphicon-search"></span>

<h1>Findr</h1>
<p>Find free wifi in NYC!</p>
<a href="<%= new_user_url %>"><h2>Sign Up!</h2></a>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<form action="<%= users_url %>" method="post">
  <%= render partial: "shared/user" %>
  
  <input type="submit" value="Sign Up">
</form>

app/views/users/show.html.erb
<h3><%= @user.username %></h3>